h12066
s 00005/00005/00020
d D 5.3 88/01/03 00:28:51 bostic 5 4
c neither K&R or ANSI C allow untyped function declarations
e
s 00000/00003/00025
d D 5.2 87/04/07 15:51:39 mckusick 4 3
c port for tahoe from Nir peleg of CCI
e
s 00007/00003/00021
d D 5.1 85/06/06 16:06:15 dist 3 2
c Add copyright
e
s 00001/00001/00023
d D 1.2 82/01/18 22:14:47 linton 2 1
c sccsid
e
s 00024/00000/00000
d D 1.1 82/01/18 19:02:33 linton 1 0
c date and time created 82/01/18 19:02:33 by linton
e
u
U
t
T
I 1
D 3
/* Copyright (c) 1982 Regents of the University of California */

D 2
static char sccsid[] = "%Z%%M% %I% %G%";
E 2
I 2
/* static char sccsid[] = "%Z%%M% %I% %G%"; */
E 3
I 3
/*
 * Copyright (c) 1980 Regents of the University of California.
 * All rights reserved.  The Berkeley software License Agreement
 * specifies the terms and conditions for redistribution.
 *
 *	%W% (Berkeley) %G%
 */
E 3
E 2

/*
 * Definitions for the command module.
 *
 * The command module scans and parses the commands.  This includes
 * input file management (i.e. the "source" command), and some error
 * handling.
 */

char *initfile;		/* file to read initial commands from */
BOOLEAN nlflag;		/* for error and signal recovery */
D 4

#define HELPFILE "/vb/arpa/linton/lib/pdx.help"

E 4
D 5
prompt();		/* print a prompt */
E 5
I 5
int prompt();		/* print a prompt */
E 5
int yyparse();		/* parser generated by yacc */
D 5
lexinit();		/* initialize debugger symbol table */
gobble();		/* eat input up to a newline for error recovery */
remake();		/* recompile program, read in new namelist */
alias();		/* create an alias */
E 5
I 5
int lexinit();		/* initialize debugger symbol table */
int gobble();		/* eat input up to a newline for error recovery */
int remake();		/* recompile program, read in new namelist */
int alias();		/* create an alias */
E 5
BOOLEAN isstdin();	/* input is from standard input */
E 1
