h58816
s 00000/00000/00031
d D 6.1 86/05/22 15:04:04 kjd 3 2
c document for 4.3BSD release
e
s 00000/00000/00031
d D 5.1 86/05/22 15:03:57 kjd 2 1
c document distributed with 4.2BSD
e
s 00031/00000/00000
d D 4.1 86/05/22 15:03:50 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
.ds ZZ \fB.\|.\|.\fP
.ds ST \v'.3m'\s+2*\s0\v'-.3m'
.ds DO \h'\w'do 'u'
.ds Ca \h'\w'case 'u'
.ds WH \h'\w'while 'u'
.ds VT \|\fB\(or\fP\|
.ds TH \h'\w'then 'u'
.ds DC \*(DO\*(CA
.ds AP >\h'-.2m'>
.ds HE <\h'-.2m'<
..	\" macros for algol 68c reference manual
.ds DA 1977 November 1
.ds md \v'.25m'
.ds mu \v'-.25m'
.ds U \*(mu\s-3
.ds V \s0\*(md
.ds L \*(md\s-3
.ds M \s0\*(mu
.ds S \s-1
.ds T \s0
..	\" small 1
.ds O \*S1\*T
.ds h \|
.ds s \|\|
..	\" ellipsis
.ds e .\|.\|.
..	\" subscripts
.ds 1 \*(md\s-41\s0\*(mu
.ds 2 \*(md\s-42\s0\*(mu
E 1
