h01554
s 00011/00050/00025
d D 6.2 86/05/10 14:16:52 bloom 4 3
c macros rewritten and simplified
e
s 00000/00000/00075
d D 6.1 86/04/25 02:19:49 cuccia 3 2
c Mark Seiden edits for 4.3BSD release
e
s 00000/00000/00075
d D 5.1 86/04/25 02:19:43 cuccia 2 1
c document distributed with 4.2BSD
e
s 00075/00000/00000
d D 4.1 86/04/25 02:19:38 cuccia 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 4
.fp 3 CW
.fz 3 -1
.fz S 3 -0
.bd S 3 3	\" embolden special font in context of 3
.if t .nr PI .25i	\" paragraph indent
.nr PS 10	\" text point size
.nr VS 12	\" text vertical (inter-line) spacing
.nr dP 1	\" delta point size for program
.ps \n(PS
.vs \n(VS
.if n .nr NH 1	\" space after NH or SH heading
.if t .nr NH .5v
.if n .ls 2
E 4
I 4
.\"	@(#)p.mac	6.1 (Berkeley) 4/25/86
.\"
E 4
.de UC
\&\\$3\s-1\\$1\\s0\&\\$2
..
.de IT
D 4
.if n .ul
\&\\$3\f2\\$1\fR\^\&\\$2
E 4
I 4
\&\\$3\fI\\$1\fR\^\&\\$2
E 4
..
.de UL
D 4
.lg 0
.if n .ul
\%\&\\$3\f3\\$1\fR\&\\$2
.lg
E 4
I 4
\%\&\\$3\f(CW\s-1\\$1\s0\fR\&\\$2
E 4
..
D 4
.cs 3 25 \\n(PS-1	\" constant space
.nr P \\n(PS	\" current point size
.nr S \\n(PS+1	\" 1 points bigger
.nr s \\n(PS-1	\" 1 points smaller
E 4
.de P1
.DS I .5i
.nf
D 4
.lg 0
.if n .ls 1
.if n .ta 5 10 15 20 25 30 35 40 45 50 55 60
.if t .ps -\\n(dP
.if t .vs -\\n(dP
.nr P \\n(.s
.nr S \\n(.s+1
.nr s \\n(.s-1
.nr t 5*33u	\" width in 9 point CW
.if t .ta 1u*\\ntu 2u*\\ntu 3u*\\ntu 4u*\\ntu 5u*\\ntu 6u*\\ntu 7u*\\ntu 8u*\\ntu 9u*\\ntu 10u*\\ntu 11u*\\ntu 12u*\\ntu 13u*\\ntu 14u*\\ntu
.ft 3
.cs 3 25 \\nP-1
.lg 0
E 4
I 4
.ft CW
.ps \\n(PS-1
.vs \\n(VS-1
E 4
..
.de P2
.ps \\n(PS
D 4
.vs \\n(VSp
.nr P \\n(PS
.nr S \\n(PS+1
.nr s \\n(PS-1
E 4
I 4
.vs \\n(VS
E 4
.ft R
D 4
.if n .ls 2
.fi
E 4
.DE
D 4
.lg
.cs 3 25 \\n(PS-1
E 4
..
.hy 14	\"2=not last lines; 4= no -xx; 8=no xx-
.am SH
D 4
.ft 1
.bd 1 3
E 4
I 4
.ft R
E 4
..
.am NH
D 4
.ft 1
.bd 1 3
E 4
I 4
.ft R
E 4
..
.am TL
D 4
.ft 1
.bd 1 3
E 4
I 4
.ft R
E 4
..
E 1
