h46095
s 00001/00000/00023
d D 1.3 90/06/02 17:47:42 karels 3 2
c reorg; insert keyworks
e
s 00000/00000/00023
d D 1.2 90/06/02 17:35:48 karels 2 1
c version distributed with 4.3BSD, dated Jun 23, 1983
e
s 00023/00000/00000
d D 1.1 90/06/02 17:25:58 karels 1 0
c ancillary file for tmac.s, extracted from there;
c version distributed with 4.2BSD, named "s.*", dated Jun 23, 1983
e
u
U
t
T
I 3
.\" %W% (Berkeley) %G%
E 3
I 1
.	\" TM - U.C. Berkeley thesis mode
.ls 2
.if v .nr PO 1.5i
.rm CH
.ds RH \\n(PN
.rm CF
.P1
.nr TM 1
.	\" CT - chapter title 
.de CT
.rn RH R@
.if \\n(1T .bp
.RT
.if \\n(1T .sp
.if !\\n(1T .BG
.RT
.ft 3
.if n .ul 100
.ps \\n(PS+2
.ce 100
.nr CT 1
.rn R@ RH
..
E 1
