	/*  sccs id   @(#)  ex_vars.h  @(#)makeoptions	6.4 5/31/85  */
#define AUTOINDENT      0
#define AUTOPRINT       1
#define AUTOWRITE       2
#define BEAUTIFY        3
#define DIRECTORY       4
#define EDCOMPATIBLE    5
#define EIGHTBIT        6
#define ERRORBELLS      7
#define HARDTABS        8
#define IGNORECASE      9
#define LISP            10
#define LIST            11
#define MAGIC           12
#define MESG            13
#define MODELINE        14
#define NUMBER          15
#define OPEN            16
#define OPTIMIZE        17
#define PARAGRAPHS      18
#define PROMPT          19
#define READONLY        20
#define REDRAW          21
#define REMAP           22
#define REPORT          23
#define SCROLL          24
#define SECTIONS        25
#define SHELL           26
#define SHIFTWIDTH      27
#define SHOWMATCH       28
#define SLOWOPEN        29
#define SOURCEANY       30
#define TABSTOP         31
#define TAGLENGTH       32
#define TAGS            33
#define TERM            34
#define TERSE           35
#define TIMEOUT         36
#define TTYTYPE         37
#define WARN            38
#define WINDOW          39
#define WRAPSCAN        40
#define WRAPMARGIN      41
#define WRITEANY        42

#define	NOPTS	43
