#!/bin/sh -
#
# 4.3BSD-Quasijarus release-making script.
#
# This file is freely redistributable.
#
#	@(#)maketape	4.35 (Berkeley) 10/9/99
#

# maketape [ 6250 | 1600 [ tapename ] ]
miniroot=ra0d
tape=/dev/rmt12
type=6250
block=20
tflag=cbf

if [ $# -gt 0 ]; then
	type=$1;
fi

if [ $# -gt 1 ]; then
	tape=$2;
fi

mt -t ${tape} rew
date
cd /nbsd
sync

cd /nbsd/sys/vaxdist/tp
tp cmf /tmp/tape.$$ boot copy format
cd /nbsd/sys/mdec
echo "Build 1st level boot block file"
cat tmscpboot tsboot htboot tmboot mtboot utboot /tmp/tape.$$ | \
	dd of=${tape} obs=512 conv=sync

echo "Add image of mini-root file system"
eval dd if=/dev/r${miniroot} count=308 bs=20b conv=sync of=$tape

echo "Add full dump of real file system"
/etc/dump 0f ${tape} /dev/rra1a

echo "Add tar image of /usr"
cd /nbsd/usr
tar ${tflag} ${block} ${tape} MAKEHOSTS adm bin dict games hosts \
	include lib local man mdec msgs new old preserve pub spool tmp ucb

if [ ${type} != '6250' ]
then
	echo "Done, rewinding first tape"
	rsh $remote mt -t ${tape} rew &
	echo "Mount second tape and hit return when ready"
	echo "(or type name of next tape drive)"
	read x
	if [ "$x" != "" ]
	then	tape=$x
	fi
fi

: tape2:
echo "Add tar image of system sources"
cd /nbsd/usr/src/sys
tar ${tflag} ${block} ${tape} .

echo "Add user source code"
FILES="Makefile bin cci doc etc games include lib local man old \
	ucb undoc usr.bin usr.lib"
cd /nbsd/usr/src
tar ${tflag} ${block} ${tape} ${FILES}

echo "Done, rewinding tape"
mt -t ${tape} rew &
