#!/bin/sh -
#
# Copyright (c) 1990 The Regents of the University of California.
# All rights reserved.
#
# %sccs.include.redist.sh%
#
#	@(#)maketape	4.34 (Berkeley) 12/26/98
#

# maketape [ 6250 | 1600 [ tapename ] ]
miniroot=ra1d
tape=/dev/nrmt8
type=6250
block=20
tflag=cbf

if [ $# -gt 0 ]; then
	type=$1;
fi

if [ $# -gt 1 ]; then
	tape=$2;
fi

mt -t ${tape} rew
date
cd /nbsd
sync

cd /nbsd/sys/vaxdist/tp
tp cmf /tmp/tape.$$ boot copy format
cd /nbsd/sys/mdec
echo "Build 1st level boot block file"
cat tsboot htboot tmboot mtboot utboot noboot noboot /tmp/tape.$$ | \
        dd of=${tape} obs=512 conv=sync

echo "Add image of mini-root file system"
eval dd if=/dev/r${miniroot} count=308 bs=20b conv=sync of=$tape

echo "Add full dump of real file system"
/etc/dump 0f ${tape} /nbsd

echo "Add tar image of /usr"
cd /nbsd/usr
tar ${tflag} ${block} ${tape} MAKEHOSTS adm bin dict doc games hosts \
	include lib local man mdec msgs new preserve pub spool tmp ucb

if [ ${type} != '6250' ]
then
	echo "Done, rewinding first tape"
	rsh $remote mt -t ${tape} rew &
	echo "Mount second tape and hit return when ready"
	echo "(or type name of next tape drive)"
	read x
	if [ "$x" != "" ]
	then	tape=$x
	fi
fi

: tape2:
echo "Add tar image of system sources"
cd /nbsd/usr/src/sys
tar ${tflag} ${block} ${tape} .

echo "Add user source code"
FILES="Makefile bin cci etc games include lib local man old \
	ucb usr.bin usr.sbin"
cd /nbsd/usr/src
tar ${tflag} ${block} ${tape} ${FILES}
