#!/bin/sh -
#
#	@(#)netstart	1.1 (Berkeley) 1/10/99

routedflags=-q
rwhod=NO

# myname is my symbolic name
# my-netmask is specified in /etc/networks
#
hostname=myname.my.domain
hostname $hostname

ifconfig imp0 inet $hostname
ifconfig de0 inet $hostname netmask my-netmask
ifconfig qe0 inet $hostname netmask my-netmask

ifconfig lo0  inet localhost
route add $hostname localhost 0
hostid $hostname
