h47207
s 00001/00001/00012
d D 6.1 85/04/29 17:41:11 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00002/00012
d D 5.1 85/04/29 17:41:04 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00014/00000/00000
d D 4.1 85/04/29 17:40:56 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH CB 1
E 2
I 2
D 3
.TH CB 1 "18 January 1983"
E 3
I 3
.TH CB 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
cb \- C program beautifier
.SH SYNOPSIS
.B cb
.SH DESCRIPTION
.I Cb
places a copy of the C program from the standard input
on the standard output with spacing and indentation
that displays the structure of the program.
D 2
.SH BUGS
E 2
E 1
