h05664
s 00001/00001/00034
d D 6.1 85/04/29 21:13:49 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00035/00000/00000
d D 5.1 85/04/29 21:13:25 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH FALSE 1 "11 January 1982"
E 2
I 2
.TH FALSE 1 "%Q%"
E 2
.UC 5
.SH NAME
false, true \- provide truth values
.SH SYNOPSIS
.B true
.PP
.B false
.SH DESCRIPTION
.I True
and
.I false
are usually used in a Bourne shell script.
They test for the appropriate status "true" or "false" before running 
(or failing to run) a list of commands.  
.SH EXAMPLE
.IP
.nf
     while false
     do
          command list 
     done
.SH "SEE ALSO"
csh(1),
sh(1),
true(1)
.SH DIAGNOSTICS
.I False
has exit status nonzero.
E 1
