h00628
s 00001/00001/00026
d D 6.1 85/04/29 14:26:43 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00026
d D 5.1 85/04/29 14:26:36 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00027/00000/00000
d D 4.1 85/04/29 14:26:29 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH HEAD 1 2/24/79
E 2
I 2
D 3
.TH HEAD 1 "24 February 1979"
E 3
I 3
.TH HEAD 1 "%Q%"
E 3
E 2
.UC
.SH NAME
head \- give first few lines
.SH SYNOPSIS
.B head
[
.BR \- count
] [
file ...
]
.SH DESCRIPTION
This filter gives the first
.I count
lines of each of the specified files, or of the standard input.
If
.I count
is omitted it defaults to
10.
.SH SEE\ ALSO
tail(1)
E 1
