h11515
s 00005/00004/00836
d D 6.6 86/05/09 08:27:46 anne 8 7
c grammar
e
s 00002/00002/00838
d D 6.5 86/01/20 09:36:37 bloom 7 6
c calls to nonexistant fonts (from gbergman@cartan)
e
s 00004/00000/00836
d D 6.4 85/10/18 16:13:18 mckusick 6 5
c add ~b documentation
e
s 00022/00002/00814
d D 6.3 85/09/15 17:32:52 serge 5 4
c added Replyall and PAGER variables, and unread/Unread command
e
s 00007/00002/00809
d D 6.2 85/09/10 21:01:14 serge 4 3
c corrected documentation for "write" command
e
s 00026/00003/00785
d D 6.1 85/04/29 14:34:26 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00305/00067/00483
d D 5.1 85/04/29 14:33:56 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00550/00000/00000
d D 4.1 85/04/29 14:33:39 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH MAIL 1
E 2
I 2
D 3
.TH MAIL 1 "1 April 1983"
E 3
I 3
.TH MAIL 1 "%Q%"
E 3
E 2
.UC 4
.SH NAME
mail \- send and receive mail
.SH SYNOPSIS
.B mail
[
I 2
.B \-v
]
[
.B \-i
]
[
.B \-n
]
[
.B \-s
subject
]
[
user ...
]
.br
.B mail
[
.B \-v
]
[
.B \-i
]
[
.B \-n
]
E 2
.B \-f
[
name
]
I 2
.br
.B mail
[
.B \-v
E 2
]
[
D 2
people ...
E 2
I 2
.B \-i
E 2
]
I 2
[
.B \-n
]
.B \-u
user
E 2
.SH INTRODUCTION
.I Mail
is a intelligent mail processing system, which has
a command syntax reminiscent of
.I ed
with lines replaced by messages.
.PP
I 2
The
.B \-v
flag puts mail into verbose mode; the details of
delivery are displayed on the users terminal.
The
.B \-i
flag causes tty interrupt signals to be ignored. This is
particularly useful when using
.I mail
on noisy phone lines.
The
.B \-n
flag inhibits the reading of /usr/lib/Mail.rc.
.PP
E 2
.I "Sending mail.\ "
D 8
To send a message to one or more other people,
E 8
I 8
To send a message to one or more people,
E 8
.I mail
D 8
can be invoked with arguments which are the names of people to
send to.  You are then expected to type in your message, followed
E 8
I 8
can be invoked with arguments which are the names of people to 
whom the mail will be sent.  You are then expected to type in 
your message, followed
E 8
by an \s-2EOT\s0 (control\-D) at the beginning of a line.
I 2
A subject may be specified on the command line by using the
.B \-s
flag. (Only the first argument after the
.B \-s
flag is used as a subject; be careful to quote subjects
containing spaces.)
E 2
The section below, labeled
.I "Replying to or originating mail,"
describes some features of
.I mail
available to help you compose your letter.
.PP
.I "Reading mail.\ "
D 2
In normal usage,
E 2
I 2
In normal usage
E 2
.I mail
is given no arguments and checks your mail out of the
post office, then
D 2
printing out a one line header of each message there.
E 2
I 2
prints out a one line header of each message there.
E 2
The current message is initially the first message (numbered 1)
and can be printed using the
.B print
command (which can be abbreviated \fBp\fR).
You can move among the messages much as you move between lines in
D 2
.I ed,
E 2
I 2
.IR ed ,
E 2
with the commands `+' and `\-' moving backwards and forwards, and
D 2
simple numbers typing the addressed message.
E 2
I 2
simple numbers.
E 2
.PP
.I "Disposing of mail.\ "
After examining a message you can
.B delete
(\fBd\fR)
the message or
.B reply
(\fBr\fR)
to it.
Deletion causes the
.I mail
program to forget about the message.
D 2
This is not irreversible, the message can be
E 2
I 2
This is not irreversible; the message can be
E 2
.B undeleted
(\fBu\fR)
by giving its number, or the
.I mail
session can be aborted by giving the
.B exit
(\fBx\fR)
command.
Deleted messages will, however, usually disappear never to be seen again.
.PP
.I "Specifying messages.\ "
Commands such as
.B print
and
.B delete
D 2
often can be given a list of message numbers as argument to apply
E 2
I 2
can be given a list of message numbers as arguments to apply
E 2
to a number of messages at once.
Thus ``delete 1 2'' deletes messages 1 and 2, while ``delete 1\-5''
deletes messages 1 through 5.
The special name ``*'' addresses all messages, and ``$'' addresses
the last message; thus the command
.B top
which prints the first few lines of a message could be used in
``top *'' to print the first few lines of all messages.
.PP
.I "Replying to or originating mail.\ "
You can use the
.B reply
command to
set up a response to a message, sending it back to the
person who it was from.
D 2
Text you then type in, up to an end-of-file (or a line consisting only
of a ``.'') defines the contents of
the message.
E 2
I 2
Text you then type in, up to an end-of-file,
defines the contents of the message.
E 2
While you are composing a message,
.I mail
treats lines beginning with the character `~' specially.
For instance, typing ``~m'' (alone on a line) will place a copy
of the current message into the response right shifting it by a tabstop.
Other escapes will set up subject fields, add and delete recipients
to the message and allow you to escape to an editor to revise the
message or to a shell to run some commands.  (These options
D 2
will be given in the summary below.)
E 2
I 2
are given in the summary below.)
E 2
.PP
.I "Ending a mail processing session.\ "
You can end a
.I mail
session with the
.B quit
(\fBq\fR)
command.
Messages which have been examined go to your
.I mbox
file unless they have been deleted in which case they are discarded.
Unexamined messages go back to the post office.
The
.B \-f
option causes
.I mail
to read in the contents of your
.I mbox
(or the specified file)
for processing; when you
D 2
.B quit
E 2
I 2
.BR quit ,
E 2
.I mail
writes undeleted messages back to this file.
I 2
The
.B \-u
flag is a short way of doing
"mail
.B \-f
/usr/spool/mail/user".
E 2
.PP
.I "Personal and systemwide distribution lists.\ "
It is also possible to create a personal distribution lists so that,
for instance, you can send mail to ``cohorts'' and have it go
to a group of people.
Such lists can be defined by placing a line like
.IP
D 2
alias cohorts bill ozalp sklower jkf mark cory:kridle
E 2
I 2
alias cohorts bill ozalp jkf mark kridle@ucbcory
E 2
.PP
in the file \&.mailrc in your home directory.
D 2
The current list of such aliases can be displayed by the
E 2
I 2
The current list of such aliases can be displayed with the
E 2
.B alias
.B (a)
command in
D 2
.I mail.
E 2
I 2
.IR mail .
E 2
System wide distribution lists can be created by editing
/usr/lib/aliases, see
.IR aliases (5)
and
D 2
.IR delivermail (8);
these are kept in a slightly different syntax.
E 2
I 2
.IR sendmail (8);
these are kept in a different syntax.
E 2
In mail you send, personal aliases will be expanded in mail sent
to others so that they will be able to \fBreply\fR to the recipients.
System wide \fIaliases\fR are not expanded when the mail is sent,
but any reply returned to the machine will have the system wide
alias expanded as all mail goes through
D 2
.I delivermail.
If you edit
/usr/lib/aliases, you must run the program
.IR newaliases (1).
E 2
I 2
.IR sendmail .
E 2
.PP
.I "Network mail (ARPA, UUCP, Berknet)\ "
D 2
Mail to sites on the ARPA network and sites within Bell laboratories
can be sent using ``name@site'' for ARPA-net sites or ``machine!user''
for Bell labs sites, provided appropriate gateways are known to the
system.  (Be sure to escape the ! in Bell sites when giving it on a
.I csh
command line by preceding it with an \e.
Machines on an instance of the Berkeley network are addressed as
``machine:user'', e.g. ``csvax:bill''.  When addressed from the
arpa-net, ``csvax:bill'' is known as ``csvax.bill@berkeley''.
E 2
I 2
See
.IR mailaddr(7)
for a description of network addresses.
E 2
.PP
.I Mail
D 2
has a number of options which can be
.B set
in the
E 2
I 2
has a number of options which can be set in the
E 2
.I \&.mailrc
file to alter its behavior; thus ``set askcc'' enables the ``askcc''
feature.  (These options are summarized below.)
.SH SUMMARY
(Adapted from the `Mail Reference Manual')
I 2
.PP
E 2
Each command is typed on a line by itself, and may take arguments
following the command word.  The command need not be typed in its
entirety \- the first command which matches the typed prefix is used.
D 2
For the commands which take message lists as arguments, if no message
E 2
I 2
For commands which take message lists as arguments, if no message
E 2
list is given, then the next message forward which satisfies the
command's requirements is used.  If there are no messages forward of
the current message, the search proceeds backwards, and if there are no
good messages at all,
.I mail
types ``No applicable messages'' and
aborts the command.
.TP 12n
.B \-
Goes to the previous message and prints it out.  If given a numeric
argument
D 2
.I n ,
E 2
I 2
.IR n ,
E 2
goes to the
D 2
.I n th
E 2
I 2
.IR n -th
E 2
previous message and prints it.
.TP
.B ?
Prints a brief summary of commands.
.TP
.B !
Executes the \s-2UNIX\s0 shell command which follows.
.TP
I 2
.B Print
(\fBP\fR)
Like
.B print
but also prints out ignored header fields. See also
.B print
I 3
,
.B ignore
E 3
and
D 3
.B ignore.
E 3
I 3
.B retain.
E 3
.TP
.B Reply
D 7
(\fRR\fR)
E 7
I 7
(\fBR\fR)
E 7
Reply to originator. Does not reply to other
recipients of the original message.
.TP
.B Type
D 7
(\fTT\fR)
E 7
I 7
(\fBT\fR)
E 7
Identical to the
.B Print
command.
.TP
E 2
.B alias
(\fBa\fR) With no arguments, prints out all currently-defined aliases.  With one
D 2
argument, prints out that alias.  With more than one argument, adds the
users named in the second and later arguments to the alias named in the
first argument.
E 2
I 2
argument, prints out that alias.  With more than one argument, creates
an new or changes an on old alias.
E 2
.TP
I 2
.B alternates
(\fBalt\fR)
The
.B alternates
command is useful if you have accounts on several machines.
It can be used to inform
.I mail
that the listed addresses are really you. When you
.B reply
to messages,
.I mail
will not send a copy of the message to any of the addresses
listed on the
.I alternates
list. If the
.B alternates
command is given with no argument, the current set of alternate
names is displayed.
.TP
E 2
.B chdir
(\fBc\fR) Changes the user's working directory to that specified, if given.  If
no directory is given, then changes to the user's login directory.
.TP
I 2
.B copy
(\fBco\fR)
The
.B copy
command does the same thing that
.B save 
does, except that it does not mark the messages it
is used on for deletion when you quit.
.TP
E 2
.B delete
(\fBd\fR) Takes a list of messages as argument and marks them all as deleted.
Deleted messages will not be saved in
D 2
.I mbox ,
E 2
I 2
.IR mbox ,
E 2
nor will they be available for most other commands.  
.TP
.B dp
(also \fBdt\fR) Deletes the current message and prints the next message.
If there is no next message, 
.I mail
says ``at EOF.''
.TP
.B edit
(\fBe\fR) Takes a list of messages and points the text editor at each one in
turn.  On return from the editor, the message is read back in.
.TP
.B exit
(\fBex\fR or \fBx\fR) Effects an immediate return to the Shell without
modifying the user's system mailbox, his
.I mbox
file, or his edit file in
D 2
.B \-f .
E 2
I 2
.BR \-f .
E 2
.TP
I 2
.B file
(\fBfi\fR)
The same as
.BR folder .
.TP
.B folders
List the names of the folders in your folder directory.
.TP
.B folder
(\fBfo\fR)
The
.B folder
command switches to a new mail file or folder. With no
arguments, it tells you which file you are currently reading.
If you give it an argument, it will write out changes (such
as deletions) you have made in the current file and read in
the new file. Some special conventions are recognized for
the name. # means the previous file, % means your system
mailbox, %user means user's system mailbox, & means
your \~/mbox file, and +folder means a file in your folder
directory.
.TP
E 2
.B from
(\fBf\fR) Takes a list of messages and prints their message headers.
.TP
.B headers
(\fBh\fR) Lists the current range of headers, which is an 18 message group.  If
a ``+'' argument is given, then the next 18 message group is printed, and if
a ``\-'' argument is given, the previous 18 message group is printed.
.TP
.B help
A synonym for ?
.TP
.B hold
(\fBho\fR, also \fBpreserve\fR) Takes a message list and marks each
message therein to be saved in the
user's system mailbox instead of in
D 2
.I mbox.
E 2
I 2
.IR mbox .
E 2
Does not override the
.B delete
command.
.TP
I 2
.B ignore
I 3
.B N.B.:
.I Ignore
has been superseded by
.I retain.
.br
E 3
Add the list of header fields named to the
.IR "ignored list" .
Header fields in the ignore list are not printed
on your terminal when you print a message. This
command is very handy for suppression of certain machine-generated
header fields. The
.B Type
and
.B Print
commands can be used to print a message in its entirety, including
ignored fields. If
.B ignore
is executed with no arguments, it lists the current set of
ignored fields.
.TP
E 2
.B mail
(\fBm\fR) Takes as argument login names and distribution group names and sends
mail to those people.
.TP
I 2
.B mbox
Indicate that a list of messages be sent to
.I mbox
in your home directory when you quit. This is the default
action for messages if you do
.I not
have the
.I hold
option set.
.TP
E 2
.B next
(\fBn\fR like \fB+\fR or CR) Goes to the next message in sequence and types it.
With an argument list, types the next matching message.
.TP
.B preserve
I 2
(\fBpre\fR)
E 2
A synonym for
D 2
.B hold.
E 2
I 2
.BR hold .
E 2
.TP
.B print
D 2
(\fBp\fR) Takes a message list and types out each message on the user's
terminal.
E 2
I 2
(\fBp\fR)
Takes a message list and types out each message on the user's terminal.
E 2
.TP
.B quit
(\fBq\fR) Terminates the session, saving all undeleted, unsaved messages in
the user's
.I mbox
file in his login directory, preserving all messages marked with
.B hold
or
.B preserve
or never referenced
in his system mailbox, and removing all other messages from his system
mailbox.  If new mail has arrived during the session, the message
``You have new mail'' is given.  If given while editing a
mailbox file with the
.B \-f
flag, then the edit file is rewritten.  A return to the Shell is
effected, unless the rewrite of edit file fails, in which case the user
can escape with the
.B exit
command.
.TP
.B reply
D 2
(\fBr\fR) Takes a message list and sends mail to each message author just like
the
.B mail
command.  The default message must not be deleted.
E 2
I 2
(\fBr\fR)
Takes a message list and sends mail to the sender and all
recipients of the specified message.
The default message must not be deleted.
E 2
.TP
.B respond
A synonym for
D 2
.B reply .
E 2
I 2
.BR reply .
E 2
.TP
I 3
.B retain
Add the list of header fields named to the
.IR "retained list" .
Only the header fields in the retain list
are shown on your terminal when you print a message.
All other header fields are suppressed.
The
.B Type
and
.B Print
commands can be used to print a message in its entirety.
If
.B retain
is executed with no arguments, it lists the current set of
retained fields.
.TP
E 3
.B save
(\fBs\fR) Takes a message list and a filename and appends each message in
turn to the end of the file.  The filename in quotes, followed by the line
count and character count is echoed on the user's terminal.  
.TP
.B set
(\fBse\fR) With no arguments, prints all variable values.  Otherwise, sets
option.  Arguments are of the form
``option=value''
D 3
or
E 3
I 3
(no space before or after =) or
E 3
``option.''
.TP
.B shell
(\fBsh\fR) Invokes an interactive version of the shell.
.TP
.B size
Takes a message list and prints out the size in characters of each
message.
.TP
I 2
.B source
(\fBso\fR)
The
.B source
command reads
.I mail
commands from a file.
.TP
E 2
.B top
Takes a message list and prints the top few lines of each.  The number of
lines printed is controlled by the variable
.B toplines
and defaults to five.
.TP
.B type
(\fBt\fR) A synonym for
D 2
.B print .
E 2
I 2
.BR print .
E 2
.TP
.B unalias
Takes a list of names defined by
.B alias
commands and discards the remembered groups of users.  The group names
no longer have any significance.
.TP
.B undelete
D 5
(\fBu\fR) Takes a message list and marks each one as
E 5
I 5
(\fBu\fR) Takes a message list and marks each message as
E 5
.I not
being deleted.
.TP
I 5
.B unread
(\fBU\fR) Takes a message list and marks each message as
.I not
having been read.
.TP
E 5
.B unset
Takes a list of option names and discards their remembered values;
the inverse of
D 2
.B set .
E 2
I 2
.BR set .
E 2
.TP
.B visual
(\fBv\fR) Takes a message list and invokes the display editor on each message.
.TP
.B write
D 4
(\fBw\fR) A synonym for
D 2
.B save .
E 2
I 2
.BR save .
E 4
I 4
(\fBw\fR) Similar to
.BR save ,
except that
.I only
the message body (\fIwithout\fP the header) is saved.
Extremely useful for such tasks as sending and receiving source
program text over the message system.
E 4
E 2
.TP
.B xit
(\fBx\fR) A synonym for
D 2
.B exit .
E 2
I 2
.BR exit .
.TP
.B z
.I Mail
presents message headers in windowfuls as described under the
.B headers
command. You can move
.IR mail 's
attention forward to the next window with the
.B z
command. Also, you can move to the previous window by using
.BR z\- .
E 2
.PP
Here is a summary of the tilde escapes,
which are used when composing messages to perform
special functions.  Tilde escapes are only recognized at the beginning
of lines.  The name
``tilde\ escape''
is somewhat of a misnomer since the actual escape character can be set
by the option
.B escape.
.TP 12n
D 2
\fB~!\fRcommand
E 2
I 2
.BR ~! command
E 2
Execute the indicated shell command, then return to the message.
.TP
I 6
\fB~b\fR name ...
Add the given names to the list of carbon copy recipients but do not make
the names visible in the Cc: line ("blind" carbon copy).
.TP
E 6
\fB~c\fR name ...
Add the given names to the list of carbon copy recipients.
.TP
.B ~d
Read the file ``dead.letter'' from your home directory into the message.
.TP
.B ~e
Invoke the text editor on the message collected so far.  After the
editing session is finished, you may continue appending text to the
message.
.TP
I 2
\fB~f\fR messages
Read the named messages into the message being sent.
If no messages are specified, read in the current message.
.TP
E 2
.B ~h
Edit the message header fields by typing each one in turn and allowing
the user to append text to the end or modify the field by using the
current terminal erase and kill characters.
.TP
\fB~m\fR messages
Read the named messages into the message being sent, shifted right one
tab.  If no messages are specified, read the current message.
.TP
.B ~p
Print out the message collected so far, prefaced by the message header
fields.
.TP
.B ~q
Abort the message being sent, copying the message to
``dead.letter''
in your home directory if
.B save
is set.
.TP
\fB~r\fR filename
Read the named file into the message.
.TP
\fB~s\fR string
Cause the named string to become the current subject field.
.TP
\fB~t\fR name ...
Add the given names to the direct recipient list.
.TP
.B ~v
Invoke an alternate editor (defined by the VISUAL option) on the
message collected so far.  Usually, the alternate editor will be a
screen editor.  After you quit the editor, you may resume appending
text to the end of your message.
.TP
\fB~w\fR filename
Write the message onto the named file.
.TP
\fB~\||\|\fRcommand
Pipe the message through the command as a filter.  If the command gives
no output or terminates abnormally, retain the original text of the
message.  The command
.IR fmt (1)
is often used as
.I command
to rejustify the message.
.TP
D 2
\fB~~\fRstring
E 2
I 2
.BR ~~ string
E 2
Insert the string of text in the message prefaced by a single ~.  If
you have changed the escape character, then you should double
that character in order to send it.
.PP
Options are controlled via the
.B set
and
.B unset
commands.  Options may be either binary, in which case it is only
D 8
significant to see whether they are set or not, or string, in which
E 8
I 8
significant to see whether they are set or not; or string, in which
E 8
case the actual value is of interest.
The binary options include the following:
.TP 15n
.B append
Causes messages saved in
.I mbox
to be appended to the end rather than prepended.
(This is set in
/usr/lib/Mail.rc
on version 7 systems.)
.TP
.B ask
Causes
.I mail
to prompt you for the subject of each message you send.  If
you respond with simply a newline, no subject field will be sent.
.TP
.B askcc
Causes you to be prompted for additional carbon copy recipients at the
end of each message.  Responding with a newline indicates your
satisfaction with the current list.
.TP
.B autoprint
Causes the
.B delete
command to behave like
.B dp
\- thus, after deleting a message, the next one will be typed
automatically.
.TP
I 2
.B debug
Setting the binary option
.I debug
is the same as specifying
.B \-d
on the command line and causes
.I mail
to output all sorts of information useful for debugging
.IR mail .
.TP
.B dot
The binary option
.I dot
causes
.I mail
to interpret a period alone on a line as the terminator
of a message you are sending.
.TP
.B hold
This option is used to hold messages in the system mailbox
by default.
.TP
E 2
.B ignore
Causes interrupt signals from your terminal to be ignored and echoed as
@'s.
.TP
I 2
.B ignoreeof
An option related to
.I dot
is
.I ignoreeof
which makes
.I mail
refuse to accept a control-d as the end of a message.
.I Ignoreeof
also applies to
.I mail
command mode.
.TP
E 2
.B metoo
Usually, when a group is expanded that contains the sender, the sender
is removed from the expansion.  Setting this option causes the sender
to be included in the group.
.TP
I 2
.B nosave
Normally, when you abort a message with two \s-2RUBOUT\s0,
.I mail
copies the partial letter to the file ``dead.letter''
in your home directory. Setting the binary option
.I nosave
prevents this.
.TP
I 5
.B Replyall
Reverses the sense of
.I reply
and
.I Reply
commands.
.TP
E 5
E 2
.B quiet
Suppresses the printing of the version when first invoked.
.TP
D 2
.B save
Causes the message collected prior to a interrupt to be saved on
the file
``dead.letter''
in your home directory on receipt of two interrupts (or after a \fB~q\fR.)
E 2
I 2
.B verbose
Setting the option
.I verbose
is the same as using the
.B \-v
flag on the command line. When mail runs in verbose mode,
the actual delivery of messages is displayed on he users
terminal.
E 2
.PP
The following options have string values:
.TP 15n
EDITOR
Pathname of the text editor to use in the
.B edit
command and ~e escape.  If not defined, then a default editor is used.
.TP
I 5
PAGER
Pathname of the program to use in the
.B more
command or when
.I crt
variable is set.  A default paginator is used if this option is
not defined.
.TP
E 5
SHELL
Pathname of the shell to use in the
.B !
command and the ~! escape.  A default shell is used if this option is
not defined.
.TP
VISUAL
Pathname of the text editor to use in the
.B visual
command and ~v escape.
.TP
I 2
.B crt
The valued option
.I crt
is used as a threshold to determine how long a message must
be before
D 5
.I more
E 5
I 5
.B PAGER
E 5
is used to read it.
.TP
E 2
.B escape
If defined, the first character of this option gives the character to
use in the place of ~ to denote escapes.
.TP
I 2
.B folder
The name of the directory to use for storing folders of
messages. If this name begins with a `/',
.I mail
considers it to be an absolute pathname; otherwise, the
folder directory is found relative to your home directory.
.TP
E 2
.B record
If defined, gives the pathname of the file used to record all outgoing
mail.  If not defined, then outgoing mail is not so saved.
.TP
.B toplines
If defined, gives the number of lines of a message to be printed out
with the
.B top
command; normally, the first five lines are printed.
.SH FILES
.if n .ta 2.5i
.if t .ta 1.8i
/usr/spool/mail/*	post office
.br
~/mbox	your old mail
.br
~/.mailrc	file giving initial mail commands
.br
/tmp/R#	temporary for editor escape
.br
/usr/lib/Mail.help*	help files
.br
/usr/lib/Mail.rc	system initialization file
.br
D 2
/bin/mail	to do actual mailing
.br
/etc/delivermail	postman
E 2
I 2
Message*	temporary for editing messages
E 2
.SH "SEE ALSO"
D 2
binmail(1), fmt(1), newaliases(1), aliases(5), delivermail(8)
E 2
I 2
binmail(1), fmt(1), newaliases(1), aliases(5),
E 2
.br
I 2
mailaddr(7), sendmail(8)
.br
E 2
`The Mail Reference Manual'
I 2
.SH BUGS
There are many flags that are not documented here. Most are
not useful to the general user.
.br
Usually,
.I mail
is just a link to
.IR Mail ,
which can be confusing.
E 2
.SH AUTHOR
Kurt Shoens
D 2
.SH BUGS
E 2
E 1
