h47896
s 00001/00001/00013
d D 6.1 85/04/29 17:53:25 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00013
d D 5.1 85/04/29 17:53:12 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00014/00000/00000
d D 4.1 85/04/29 17:52:59 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH REV 1 
E 2
I 2
D 3
.TH REV 1  "18 January 1983"
E 3
I 3
.TH REV 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
rev \- reverse lines of a file
.SH SYNOPSIS
.B rev
[ file ] ...
.SH DESCRIPTION
.I Rev
copies the named files to the standard output,
reversing the order of characters in every line.
If no file is specified, the standard input is copied.
E 1
