h46710
s 00001/00001/00149
d D 6.1 85/04/29 17:57:39 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00058/00021/00092
d D 5.1 85/04/29 17:57:26 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00113/00000/00000
d D 4.1 85/04/29 17:57:16 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH SPELL 1 
E 2
I 2
D 3
.TH SPELL 1 "12 September 1983"
E 3
I 3
.TH SPELL 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
spell, spellin, spellout \- find spelling errors
.SH SYNOPSIS
.B spell
D 2
[ option ] ...
[ file ] ...
E 2
I 2
[
.B \-v
] [
.B \-b
] [
.B \-x
] [
.B \-d
hlist ] [
.B \-s
hstop ] [
.B \-h
spellhist
] [ file ] ...
E 2
.PP
.B spellin
[ list ]
.PP
.B spellout
[
.B \-d
] list
.SH DESCRIPTION
.I Spell
collects words from the named documents,
and looks them up in a spelling list.
Words that neither occur among nor are derivable
(by applying certain inflections,
prefixes or suffixes) from words in the spelling list
are printed on the standard output.
If no files are named,
words are collected from the standard input.
.PP
.I Spell
ignores most
.I troff,
.I tbl
and
.IR  eqn (1)
constructions.
.PP
Under the
.B \-v
option, all words not literally in the spelling list are printed,
and plausible derivations from spelling list words are indicated.
.PP
Under the 
.B \-b
option, British spelling is checked.
Besides preferring
.ft I
centre, colour, speciality, travelled,
.ft R
etc.,
this option insists upon
.I -ise
in words like
.I standardise,
D 2
Fowler and the OED to the contrary
notwithstanding.
E 2
I 2
Fowler and the OED to the contrary notwithstanding.
E 2
.PP
Under the 
.B \-x
option, every plausible stem is printed with `=' for each word.
.PP
D 2
The spelling list is based on many sources,
and while more haphazard than an ordinary
dictionary, is also more effective in respect to
E 2
I 2
The spelling list is based on many sources.
While it is more haphazard than an ordinary
dictionary, it is also more effective with
E 2
proper names and popular technical words.
Coverage of
the specialized vocabularies of biology,
medicine and chemistry is light.
.PP
D 2
Pertinent auxiliary files may be specified by
name arguments, indicated below with their
default settings.
E 2
I 2
The auxiliary files used for the spelling list,
stop list, and history file may be specified by
arguments following the
.BR \-d ,
.BR \-s ,
and
.B \-h
options.
The default files are indicated below.
E 2
Copies of all output
D 2
are accumulated in the history file.
E 2
I 2
may be accumulated in the history file.
E 2
The stop list filters out misspellings (e.g. thier=thy\-y+ier)
that would otherwise pass.
.PP
Two routines help maintain the hash lists used by
.I spell.
D 2
Both expect a list of words, one per line,
E 2
I 2
Both expect a set of words, one per line,
E 2
from the standard input.
.I Spellin
D 2
adds the words on the standard input to the
E 2
I 2
combines the words from the standard input and the
E 2
preexisting
.I list
D 2
and places a new list on the standard output.
E 2
I 2
file and places a new list on the standard output.
E 2
If no 
.I list
D 2
is specified, the new list is created from scratch.
E 2
I 2
file is specified, the new list is created from scratch.
E 2
.I Spellout
D 2
looks up each word in the standard input and prints
E 2
I 2
looks up each word from the standard input and prints
E 2
on the standard output
those that are missing from (or present on, with
option
.BR \-d )
D 2
the hash list.
E 2
I 2
the hashed
.I list
file.
For example, to verify that
.I hookey
is not on the default spelling list, add it to your own
private list, and then use it with
.IR spell ,
.PP
.RS
.nf
echo  hookey  |  spellout  /usr/dict/hlista
echo  hookey  |  spellin  /usr/dict/hlista  >  myhlist
spell  \-d  myhlist  huckfinn
.RE
E 2
.SH FILES
D 2
D=/usr/dict/hlist[ab]: hashed spelling lists, American & British
E 2
I 2
/usr/dict/hlist[ab]	hashed spelling lists, American & British, default for
.B \-d
E 2
.br
D 2
S=/usr/dict/hstop: hashed stop list
E 2
I 2
/usr/dict/hstop		hashed stop list, default for
.B \-s
E 2
.br
D 2
H=/usr/dict/spellhist: history file
E 2
I 2
/dev/null		history file, default for
.B \-h
E 2
.br
I 2
/tmp/spell.$$\(**		temporary files
.br
E 2
/usr/lib/spell
.br
I 2
.SH SEE ALSO
E 2
deroff(1), sort(1), tee(1), sed(1)
.SH BUGS
The spelling list's coverage is uneven;
new installations will probably wish to 
monitor the output for several months to gather
local additions.
.br
British spelling was done by an American.
E 1
