h53680
s 00001/00001/00026
d D 6.1 85/04/29 18:01:56 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00001/00026
d D 5.1 85/04/29 18:01:49 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00027/00000/00000
d D 4.1 85/04/29 18:01:41 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH TEE 1 
E 2
I 2
D 3
.TH TEE 1  "18 January 1983"
E 3
I 3
.TH TEE 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
tee \- pipe fitting
.SH SYNOPSIS
.B tee
[
.B \-i
] [
.B \-a
]
[ file ] ...
.SH DESCRIPTION
.I Tee
transcribes the standard input to the standard
output and makes copies in the 
.I files.
Option
.B \-i
ignores interrupts;
option
.B \-a
causes the output to be appended to the
.I files
rather than overwriting them.
E 1
