h60241
s 00001/00001/00015
d D 6.1 85/04/29 18:07:22 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00005/00002/00011
d D 5.1 85/04/29 18:07:10 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00013/00000/00000
d D 4.1 85/04/29 18:06:59 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH TTY 1 
E 2
I 2
D 3
.TH TTY 1 "10 February 1983"
E 3
I 3
.TH TTY 1 "%Q%"
E 3
E 2
.AT 3
.SH NAME
tty \- get terminal name
.SH SYNOPSIS
.B tty
I 2
[ -s ]
E 2
.SH DESCRIPTION
.I Tty
D 2
prints the pathname of the user's terminal.
E 2
I 2
prints the pathname of the user's terminal unless the \-s
(silent) is given. In either case, the exit value is zero if the
standard input is a terminal and one if it is not.
E 2
.SH DIAGNOSTICS
`not a tty' if the standard input file is not a terminal.
E 1
