h22131
s 00001/00001/00019
d D 6.2 87/01/28 14:33:01 bostic 6 4
c add entries to see also
e
s 00005/00003/00017
d R 6.2 86/12/10 07:04:24 bostic 5 4
c document the argument file
e
s 00001/00001/00019
d D 6.1 85/04/29 17:29:13 mckusick 4 2
c 4.3BSD beta release manual page
e
s 00000/00000/00020
d R 6.1 85/04/29 15:06:55 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00002/00003/00018
d D 5.1 85/04/29 15:06:46 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00021/00000/00000
d D 4.1 85/04/29 15:06:37 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH USERS 1
E 2
I 2
D 4
.TH USERS 1 January 1983"
E 4
I 4
.TH USERS 1 "%Q%"
E 4
E 2
.UC
.SH NAME
users \- compact list of users who are on the system
.SH SYNOPSIS
.B users
.SH DESCRIPTION
.I Users
lists the login names of the users currently on the system in a compact,
one-line format.
.SH FILES
/etc/utmp
.SH SEE ALSO
D 2
finger(1), who(1)
.SH BUGS
E 2
I 2
D 6
who(1)
E 6
I 6
finger(1), last(1), who(1), utmp(5)
E 6
E 2
E 1
