h13751
s 00008/00001/00034
d D 6.5 04/10/20 23:06:00 msokolov 7 6
x 5
c originates from 3BSD, restore credit to William Joy
c restore note about whatis being part of man
e
s 00016/00017/00017
d D 6.4 87/06/30 20:54:44 bostic 6 5
c document the M flag, no longer part of man(1)
e
s 00000/00002/00034
d D 6.3 86/05/07 13:29:37 mckusick 5 4
c delete author
e
s 00001/00001/00035
d D 6.2 86/01/08 14:14:14 mckusick 4 3
c /usr/lib/whatis moves to /usr/man/whatis
e
s 00001/00001/00035
d D 6.1 85/04/29 15:11:08 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00003/00004/00033
d D 5.1 85/04/29 15:10:59 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00037/00000/00000
d D 4.1 85/04/29 15:10:52 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
D 6
.\" Copyright (c) 1980 Regents of the University of California.
E 6
I 6
.\" Copyright (c) 1980, 1987 Regents of the University of California.
E 6
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH WHATIS 1
E 2
I 2
D 3
.TH WHATIS 1 "18 January 1983"
E 3
I 3
.TH WHATIS 1 "%Q%"
E 3
E 2
D 7
.UC 4
E 7
I 7
.UC 3
E 7
.SH NAME
whatis \- describe what a command is
.SH SYNOPSIS
.B whatis
I 6
[
.B -M
.I path
]
E 6
command ...
.SH DESCRIPTION
D 6
.I Whatis
D 2
looks up a given command and gives the header line from the manual
section.
E 2
I 2
looks up a given command and gives the header line from the manual section.
E 2
You can then run the 
.IR man (1)
command to get more information.
If the line starts `name(section) ...' you can do
`man section name' to get the documentation for it.
Try `whatis ed' and then you should do `man 1 ed' to get the manual.
E 6
I 6
\fIWhatis\fP looks up a given command and gives the header line from the
manual page.  You can then use the \fIman\fP(1) command to get more
information.
E 6
.PP
D 6
.I Whatis
is actually just the
.B \-f
option to the
.IR man (1)
command.
E 6
I 6
Normally \fIwhatis\fP checks in a standard location (/usr/man) for its
database ``whatis''.  This can be changed by supplying a \fIpath\fP (a
la the Bourne shell) with the \fB-M\fP flag.  This search path must be
a colon (``:'') separated list of directories which \fIwhatis\fP will
search for files named ``whatis''.  The path can also be set with the
environmental variable \fIMANPATH\fP.
I 7
.PP
.I Whatis
is actually just the
.B \-f
option to the
.IR man (1)
command.
E 7
E 6
.SH FILES
.DT
D 4
/usr/lib/whatis	Data base
E 4
I 4
D 6
/usr/man/whatis	Data base
E 6
I 6
/usr/man/whatis		data base
E 6
E 4
.SH "SEE ALSO"
D 2
apropos(1), man(1), catman(8)
E 2
I 2
D 6
man(1), catman(8)
E 6
I 6
apropos(1), man(1)
E 6
E 2
D 5
.SH AUTHOR
William Joy
E 5
E 1
