h24193
s 00001/00004/00016
d D 6.2 88/01/09 18:18:36 bostic 4 3
c don't mention "rubout".
e
s 00001/00001/00019
d D 6.1 85/04/29 15:12:57 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00006/00011/00014
d D 5.1 85/04/29 15:12:50 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00025/00000/00000
d D 4.1 85/04/29 15:12:43 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH YES 1 
E 2
I 2
D 3
.TH YES 1  "18 January 1983"
E 3
I 3
.TH YES 1 "%Q%"
E 3
E 2
.UC 4
.SH NAME
yes \- be repetitively affirmative
.SH SYNOPSIS
.B yes
[
D 2
.B expletive
E 2
I 2
.I expletive
E 2
]
.SH DESCRIPTION
D 2
.B Yes
repeatedly outputs \*(lqy\*(rq,
or if
.B expletive
is given,
that is output repeatedly.
Termination is by rubout.
.SH BUGS
Boring.
E 2
I 2
D 4
.I Yes
repeatedly outputs \*(lqy\*(rq, or if
.I expletive
is given, that is output repeatedly.  Termination is by rubout.
E 4
I 4
\fIYes\fP outputs \fIexpletive\fP, or, by default, \*(lqy\*(rq, forever.
E 4
E 2
E 1
