h09216
s 00034/00000/00006
d D 6.1 86/05/23 11:58:50 kjd 3 2
c document distributed with 4.3BSD
e
s 00000/00024/00006
d D 5.1 86/05/23 11:58:45 kjd 2 1
c document distributed with 4.2BSD
e
s 00030/00000/00000
d D 4.1 86/05/23 11:58:40 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
I 3
.eh 'USD:7-%''Mail Reference Manual'
.oh 'Mail Reference Manual''USD:7-%'
.if n \
.nr fs .5v
.\".he 'Mail Reference Manual'\n(mo/\n(dy/\n(yr'%'
.tp
.sp 1.0i
.sz 12
.rb
.(l C
MAIL REFERENCE MANUAL
.)l
.sz 10
.sp 2
.i
.(l C
Kurt Shoens
.)l
.r
.(l C
Revised by
.)l
.i
.(l C
Craig Leres
.)l
.r
.(l C
Version 5.2


\*(td
.)l
.pn 2
E 3
D 2
.if n \
.nr fs .5v
.he 'Mail Reference Manual'\n(mo/\n(dy/\n(yr'%'
.tp
.sp 1.5i
.sz 12
.rb
.(l C
MAIL REFERENCE MANUAL
.)l
.sz 10
.sp 2
.i
.(l C
Kurt Shoens
.)l
.r
.(l C
Version 1.3


\*(td
.)l
.pn 2
E 2
E 1
