h37410
s 00000/00000/00006
d D 6.1 86/05/23 12:02:38 kjd 3 2
c document distributed with 4.3BSD
e
s 00000/00000/00006
d D 5.1 86/05/23 12:02:32 kjd 2 1
c document distributed with 4.2BSD
e
s 00006/00000/00000
d D 4.1 86/05/23 12:02:26 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
E 1
