h33360
s 00031/00007/00039
d D 6.2 87/06/30 21:22:23 sam 2 1
c update addresses to reflect change form 24 to 32 bit addresses 
c in config file; rewrite cy.4 and vd.4 as well as vx.4
e
s 00046/00000/00000
d D 6.1 86/11/24 18:22:17 mckusick 1 0
c from CCI
e
u
U
t
T
I 1
.\" Copyright (c) 1986 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
.TH MEM 4 "%Q%"
.UC 7
.SH NAME
D 2
mem, kmem \- main memory
E 2
I 2
mem, kmem, vmem \- main memory
E 2
.SH DESCRIPTION
.lg
.I Mem
is a special file that is an image of the main memory
of the computer.
It may be used, for example, to examine
(and even to patch) the system.
.PP
Byte addresses in
.I mem
are interpreted as physical memory addresses.
References to non-existent locations cause errors to be returned.
.PP
Examining and patching device registers is likely
to lead to unexpected results when read-only or write-only
bits are present.
.PP
The file
.I kmem
is the same as 
.I mem
except that kernel virtual memory
rather than physical memory is accessed.
.PP
D 2
On TAHOE, the I/O page
begins at physical address 0xfff00000 of
.I kmem
and per-process data for the current process
begins at virtual 0xbffff000.
E 2
I 2
The file
.I vmem
allows access to the mapped portion of the VERSAbus
i/o space.  On the Tahoe the upper megabyte
of the physical address space is accessible through
this file (0xfff00000 through 0xffffffff). 
Accesses to the upper 64 kilobytes of
the i/o space result in VERSAbus transfers with a
16-bit address (the offset in this region) and a
``non-privileged short i/o'' VERSAbus address modifier.
Accesses to the remainder of the mapped region,
result in VERSAbus transfers with a 24-bit address
and a ``non-privileged standard'' VERSAbus address
modifier.  This region is actually part of the region
between 0xfeff0000 and 0xffff0000
which generates VERSAbus transfers with a 24-bit address.
Accesses to the remainder of the one gigabyte i/o space
generate transfers that utilize a 32-bit address with
a ``non-privileged extended'' address modifier.  Any
32-bit address generated by a cpu access to this part
of the i/o space have the upper two bits zero; thus,
for example, an access to physical address 0xfe000000
causes the address 0x3e000000 to be supplied in the
resultant VERSAbus read/write cycle.
.PP
On the Tahoe, the 
per-process data for the current process
begins at virtual address 0xbffff000.
E 2
.SH FILES
/dev/mem,
D 2
/dev/kmem
E 2
I 2
/dev/kmem,
/dev/vmm
E 2
.SH BUGS
Memory files are accessed one byte
at a time, an inappropiate method for some
device registers.
E 1
