h52625
s 00000/00000/00039
d D 6.1 86/05/22 15:46:37 kjd 3 2
c document for 4.3BSD release
e
s 00000/00000/00039
d D 5.1 86/05/22 15:46:33 kjd 2 1
c document distributed with 4.2BSD
e
s 00039/00000/00000
d D 4.1 86/05/22 15:46:28 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
.ds . \&\s+2.\s0\&
.de UC
\&\\$3\s-1\\$1\s0\\$2
..
.de UL
.if t \&\\$3\f3\\$1\f1\\$2
.if n \&\\$3\f2\\$1\f1\\$2
..
.de IT
\&\\$3\f2\\$1\fP\\$2
..
.de UI
\f3\\$1\fI\\$2\fR\\$3
..
.de P1
.if n .ls 1
.nf
.if n .ta 5 10 15 20 25 30 35 40 45 50 55 60
.if t .ta .3i .6i .9i 1.2i 1.5i 1.8i
.tr -\-
.		use first argument as indent if present
.if \\n(.$ .DS I \\$1
.if !\\n(.$ .DS I 5
.bd 1 2
..
.de P2
.br
.bd 1 2
.DE
.bd 1
.tr --
.if n .ls 2
..
.hy 14
.	2=not last lines; 4= no -xx; 8=no xx-
.tr *\(**
.nr PI .2i
E 1
