!
! BOOTSTRAP BY BOOT() SYSCALL
! BOOT FROM DEFAULT DEVICE TO A SINGLE USER SHELL
!
LOAD BOOT
D/G B 2		! BOOT PARAMETERS: RB_SINGLE
D/G A 10	! DEV TO BOOT FROM (16=RA ON KDB50, CHANGE TO 9 IF UDA50)
START 2
