h17787
s 00005/00001/00062
d D 6.4 86/06/01 00:46:13 mis 5 4
c added diagnostics.
e
s 00008/00006/00055
d D 6.3 86/05/16 15:52:35 karels 4 3
c update trailers
e
s 00022/00002/00039
d D 6.2 86/02/17 17:31:55 sklower 3 2
c Document additional diagnostics, note XNS support and caution, specify board model # to distinguish from NP100.
e
s 00001/00001/00040
d D 6.1 85/05/15 17:43:33 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00041/00000/00000
d D 5.1 85/05/15 17:43:27 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH IL 4 "27 July 1983"
E 2
I 2
.TH IL 4 "%Q%"
E 2
.UC 5
.SH NAME
D 3
il \- Interlan 10 Mb/s Ethernet interface
E 3
I 3
il \- Interlan NI1010 10 Mb/s Ethernet interface
E 3
.SH SYNOPSIS
D 4
.B "device il0 at uba0 csr 161000 vector ilrint ilcint"
E 4
I 4
.B "device il0 at uba0 csr 164000 vector ilrint ilcint"
E 4
.SH DESCRIPTION
The
.I il
interface provides access to a 10 Mb/s Ethernet network through
D 4
an Interlan controller.
E 4
I 4
an Interlan 1010 or 1010A controller.
E 4
.PP
D 4
The host's Internet address is specified at boot time with an SIOCSIFADDR
E 4
I 4
Each of the host's network addresses
is specified at boot time with an SIOCSIFADDR
E 4
ioctl.  The
.I il
interface employs the address resolution protocol described in
.IR arp (4P)
to dynamically map between Internet and Ethernet addresses on the local
network.
.PP
The interface normally tries to use a ``trailer'' encapsulation
D 4
to minimize copying data on input and output.  This may be
disabled, on a per-interface basis, by setting the IFF_NOTRAILERS
E 4
I 4
to minimize copying data on input and output.
The use of trailers is negotiated with ARP.
This negotiation may be disabled, on a per-interface basis,
by setting the IFF_NOTRAILERS
E 4
flag with an SIOCSIFFLAGS ioctl.
.SH DIAGNOSTICS
\fBil%d: input error\fP.  The hardware indicated an error
in reading a packet off the cable or an illegally sized packet.
.PP
\fBil%d: can't handle af%d\fP.  The interface was handed
a message with addresses formatted in an unsuitable address
family; the packet was dropped.
I 3
.PP
D 5
\fBil%d: setaddr failed\fP.  The interface was unable to reprogram
E 5
I 5
\fBil%d: setaddr didn't work\fP.  The interface was unable to reprogram
E 5
its physical ethernet address.
This may happen with very early models of the interface.
This facility is used only when
the controller is not the first network interface configured for XNS.
The oldest interface tested (2.7.1.0.1.45) has never failed in this way.
.PP
The following messages indicate a probable hardware error performing
the indicated operation during autoconfiguration or initialization.
The status field in the control and status register (the low-order four bits)
should indicate the nature of the failure.
See the hardware manual for details.
.PP
\fBil%d: reset failed, csr=%b\fP.
.PP
\fBil%d: status failed, csr=%b\fP.
.PP
\fBil%d: hardware diag failed, csr=%b\fP.
.PP
\fBil%d: verifying setaddr, csr=%b\fP.
I 5
.PP
\fBil%d: stray xmit interrupt, csr=%b\fP.
.PP
\fBil%d: can't initialize\fP.
E 5
E 3
.SH SEE ALSO
intro(4N), inet(4F), arp(4P)
D 4
.SH BUGS
E 4
D 3
The PUP protocol family should be added.
E 3
E 1
