h52220
s 00001/00001/00011
d D 6.1 85/05/15 17:00:42 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00003/00007/00009
d D 5.1 85/05/15 17:00:36 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00016/00000/00000
d D 4.1 85/05/15 17:00:30 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH NULL 4 
E 2
I 2
D 3
.TH NULL 4 "9 February 1983"
E 3
I 3
.TH NULL 4 "%Q%"
E 3
E 2
.AT 3
.SH NAME
null \- data sink
.SH DESCRIPTION
D 2
Data written on 
a null special file
is discarded.
E 2
I 2
Data written on a null special file is discarded.
E 2
.PP
D 2
Reads from 
a null special file
always return 0 bytes.
E 2
I 2
Reads from a null special file always return 0 bytes.
E 2
.SH FILES
/dev/null
E 1
