.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)eqnchar.7	6.2 (Berkeley) 10/20/04
.\"
.TH EQNCHAR 7 "October 20, 2004"
.UC 3
.SH NAME
eqnchar \- special character definitions for eqn
.SH SYNOPSIS
.B eqn /usr/pub/eqnchar
[ files ]
.B | troff
[ options ]
.PP
.B neqn /usr/pub/eqnchar
[ files ]
.B | nroff
[ options ]
.SH DESCRIPTION
.I Eqnchar
contains
.I troff
and
.I nroff
character definitions for constructing characters that are not
available on the Graphic Systems typesetter.
These definitions are primarily intended for use with
.I eqn
and
.IR neqn .
.PP
To print a reference card showing these characters, execute the following
commands on a machine with the typesetter:
.PP
	cd /usr/pub
.br
	eqn eqnchar eqnchar.refcard | troff
.PP
It only works on the Graphic Systems typesetter and on terminals with
half-line capabilities, and thus does not appear in this printing of the
general manual, which is done with
.I pstroff
or with
.I nroff
without assuming half-life capabilities.
.SH FILES
/usr/pub/eqnchar
.br
/usr/pub/eqnchar.refcard
.SH SEE ALSO
troff(1), eqn(1)
