h64358
s 00000/00000/00049
d D 6.1 86/05/22 14:11:54 kjd 3 2
c document for 4.3BSD release
e
s 00000/00000/00049
d D 5.1 86/05/22 14:11:40 kjd 2 1
c document distributed with 4.2BSD
e
s 00049/00000/00000
d D 4.1 86/05/22 14:11:28 kjd 1 0
c document distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
.tr |\(bv
.de IT
.if n .ul
\%\&\\$3\f2\\$1\fR\&\\$2
..
.de UL
.lg 0
.if n .ul
\%\&\\$3\f3\\$1\fR\&\\$2
.lg
..
.de UC
\\$3\s-1\\$1\s0\\$2
..
.de P1
.DS I .4i
.nf
.lg 0
.if n .ls 1
.if n .ta 5 10 15 20 25 30 35 40 45 50 55 60
.if t .ps -\\n(dP
.if t .vs -\\n(dP
.nr P \\n(.s
.nr S \\n(.s+1
.nr s \\n(.s-1
.nr t 5*33u	\" width in 9 point CW
.if t .ta 1u*\\ntu 2u*\\ntu 3u*\\ntu 4u*\\ntu 5u*\\ntu 6u*\\ntu 7u*\\ntu 8u*\\ntu 9u*\\ntu 10u*\\ntu 11u*\\ntu 12u*\\ntu 13u*\\ntu 14u*\\ntu
.ft 3
.tr _\(ul
.tr -\-
.lg 0
..
.de P2
.ps \\n(PS
.vs \\n(VSp
.nr P \\n(PS
.nr S \\n(PS+1
.nr s \\n(PS-1
.ft R
.if n .ls 2
.fi
.DE
.tr --
.tr ''
.lg
..
.nr PI .2i
E 1
