h20918
s 00001/00001/00016
d D 6.1 85/05/20 17:19:35 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00004/00008/00013
d D 5.1 85/05/20 17:18:58 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00021/00000/00000
d D 4.1 85/05/20 17:17:51 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH ALIENS 6 4/2/81
E 2
I 2
D 3
.TH ALIENS 6 "2 April 1981"
E 3
I 3
.TH ALIENS 6 "%Q%"
E 3
E 2
.UC 4
.SH NAME
aliens \- The alien invaders attack the earth
D 2
.SH SYNIOPSIS
E 2
I 2
.SH SYNOPSIS
E 2
.B /usr/games/aliens
.SH DESCRIPTION
D 2
.PP
This is a UNIX version of Space Invaders.  The program is pretty much self
documenting.
E 2
I 2
This is a UNIX version of Space Invaders. 
The program is pretty much self documenting.
E 2
.SH FILES
/usr/games/lib/aliens.log	Score file
D 2
.SH BUGS
The program is a CPU hog.  It needs to be re-written.
It doesn't do well on terminals that run slower than 9600 baud.
E 2
E 1
