h32068
s 00009/00000/00000
d D 4.1 85/04/29 20:02:12 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
.TH DIFFDIR 1 "4/1/81"
.AT 3
.pl 1
The ``diffdir'' command is obsolete, as it has been incorporated into
``diff'' by specifying ``diff dir1 dir2''.  Note, however, that the
``\-h'' option of ``diffdir'' is now the ``\-l'' option in ``diff'',
as diff already had a ``\-h'' option.
E 1
