h26057
s 00008/00000/00000
d D 4.1 85/04/29 20:14:05 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
.TH SSP 1 "4/1/81"
.AT 3
.pl 1
The ``ssp'' command is obsolete.  Use the ``-s'' (single space) option to
the ``cat'' command instead.  Thus ``nroff -ms foo.n | ssp'' is replaced
by ``nroff -ms foo.n | cat -s''.
E 1
