h49931
s 00002/00002/00032
d D 6.3 85/11/28 10:56:10 bloom 4 3
c should be long if saying it is 32 bits
e
s 00001/00001/00033
d D 6.2 85/06/28 16:57:14 sechrest 3 2
c Improved english
e
s 00001/00001/00033
d D 6.1 85/05/15 11:55:18 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00034/00000/00000
d D 5.1 85/05/15 11:55:12 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH GETHOSTID 2 "12 February 1983"
E 2
I 2
.TH GETHOSTID 2 "%Q%"
E 2
.UC 5
.SH NAME
gethostid, sethostid \- get/set unique identifier of current host
.SH SYNOPSIS
.nf
.ft B
hostid = gethostid()
D 4
int hostid;
E 4
I 4
long hostid;
E 4
.PP
.ft B
sethostid(hostid)
D 4
int hostid;
E 4
I 4
long hostid;
E 4
.fi
.SH DESCRIPTION
.I Sethostid
establishes a 32-bit identifier for the
D 3
current processor which is intended to be unique among all
E 3
I 3
current processor that is intended to be unique among all
E 3
UNIX systems in existence.  This is normally a DARPA Internet
address for the local machine.  This call is allowed only to the
super-user and is normally performed at boot time.
.PP
.I Gethostid
returns the 32-bit identifier for the current processor.
.SH SEE ALSO
hostid(1), gethostname(2)
.SH BUGS
32 bits for the identifier is too small.
E 1
