h52739
s 00001/00002/00032
d D 6.3 86/05/13 15:24:22 karels 5 4
c get serious!
e
s 00002/00002/00032
d D 6.2 86/03/04 18:52:07 donn 4 3
c Resolve lint problems -- pids are ints, not longs.
e
s 00001/00001/00033
d D 6.1 85/05/09 16:38:53 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00020/00014/00014
d D 5.1 85/05/09 16:38:46 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00028/00000/00000
d D 4.1 85/05/09 16:38:40 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH GETPID 2 
E 2
I 2
D 3
.TH GETPID 2 "12 February 1983"
E 3
I 3
.TH GETPID 2 "%Q%"
E 3
E 2
.UC 4
.SH NAME
D 2
getpid \- get process identification
E 2
I 2
getpid, getppid \- get process identification
E 2
.SH SYNOPSIS
D 2
.B getpid()
E 2
I 2
.ft B
.nf
pid = getpid()
D 4
long pid;
E 4
I 4
int pid;
E 4
.sp
ppid = getppid()
D 4
long ppid;
E 4
I 4
int ppid;
E 4
.fi
.ft R
E 2
.SH DESCRIPTION
.I Getpid
returns
the process ID of
the current process.
D 2
Most often it is used to generate
uniquely-named
temporary files.
.SH "SEE ALSO"
mktemp(3)
.SH "ASSEMBLER (PDP-11)"
(getpid = 20.)
.br
.B sys getpid
.br
(pid in r0)
E 2
I 2
D 5
Most often it is used with the host identifier
.IR gethostid (2)
E 5
I 5
Most often it is used
E 5
to generate uniquely-named temporary files.
.PP
.I Getppid
returns the process ID of the parent
of the current process. 
.SH "SEE ALSO
gethostid(2)
E 2
E 1
