h23553
s 00001/00001/00024
d D 6.1 85/05/20 16:58:24 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00002/00024
d D 5.1 85/05/20 16:58:07 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00026/00000/00000
d D 4.1 85/05/20 16:57:53 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH AARDVARK 6
E 2
I 2
D 3
.TH AARDVARK 6 "1 February 1983"
E 3
I 3
.TH AARDVARK 6 "%Q%"
E 3
E 2
.UC 4
.SH NAME
aardvark \- yet another exploration game
.SH SYNOPSIS
.B /usr/games/aardvark
.SH DESCRIPTION
Aardvark is yet another computer fantasy simulation game
of the adventure/zork genre.
This one is written in DDL (Dungeon Definition Language)
and is intended primarily as an example of how to write
a dungeon in DDL.
.SH FILES
.ta \w'/usr/games/lib/aardvark'u
/usr/games/lib/ddlrun	ddl interpreter
.br
/usr/games/lib/aardvark	internal form of aardvark dungeon
.SH AUTHOR
Mike Urban, UCLA
D 2
.SH BUGS
E 2
E 1
