h43419
s 00015/00005/00007
d D 6.2 87/04/02 20:02:18 bostic 4 3
c take args, now
e
s 00001/00001/00011
d D 6.1 85/05/20 17:11:22 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00001/00006/00011
d D 5.1 85/05/20 17:11:12 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00017/00000/00000
d D 4.1 85/05/20 17:11:04 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
I 4
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
E 4
.\"
I 4
.\"	@(#)number.6	6.6 (Berkeley) 4/1/87
.\"
.\"
E 4
D 2
.TH NUMBER 6
E 2
I 2
D 3
.TH NUMBER 6 "1 February 1983"
E 3
I 3
.TH NUMBER 6 "%Q%"
E 3
E 2
D 4
.AT 3
E 4
I 4
.UC 4
E 4
.SH NAME
number \- convert Arabic numerals to English
.SH SYNOPSIS
D 4
.B /usr/games/number
E 4
I 4
.B number
[ # ]
E 4
.SH DESCRIPTION
D 4
.I Number
copies the standard input to the standard output,
changing each decimal number to a fully spelled out version.
E 4
I 4
\fINumber\fP converts its arguments from decimal numbers to
a fully spelled-out version.  In the absence of arguments,
\fInumber\fP reads from the standard input.  Output is to
the standard output.
.SH BUGS
\fINumber\fP doesn't understand about exponents.
E 4
D 2
Punctuation is added to make the output sound well when
played through
.IR speak (1).
.SH "SEE ALSO"
speak(1)
E 2
E 1
