h33087
s 00028/00000/00000
d D 6.1 04/10/21 05:45:31 msokolov 1 0
c separated from bcd(6)
e
u
U
t
T
I 1
.\" Copyright (c) 1988 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the University of California, Berkeley.  The name of the
.\" University may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\"	%W% (Berkeley) %G%
.\"
.TH PPT 6 "%Q%"
.UC 7
.SH NAME
ppt \- format input as paper tape
.SH SYNOPSIS
\fBppt\fP [ string ]
.SH DESCRIPTION
\fIppt\fP convert command line arguments, if
provided, or standard input into a form familiar to old-timers.
.SH "SEE ALSO"
bcd(6)
E 1
