h20611
s 00114/00017/00016
d D 6.1 85/05/20 17:29:17 mckusick 3 2
c chase is replaced by robots in 4.3BSD
e
s 00001/00002/00032
d D 5.1 85/05/20 17:23:12 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00034/00000/00000
d D 4.1 85/05/20 17:22:27 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH CHASE 6 4/1/81
E 2
I 2
D 3
.TH CHASE 6 "1 April 1981"
E 2
.UC 4
E 3
I 3
.TH ROBOTS 6 "%Q%"
.UC 6
E 3
.SH NAME
D 3
chase \- Try to escape to killer robots
E 3
I 3
robots \- fight off villainous robots
E 3
.SH SYNOPSIS
D 3
.B /usr/games/chase
E 3
I 3
.B /usr/games/robots
E 3
[
D 3
.I nrobots
E 3
I 3
.B \-sjta
E 3
] [
D 3
.I nfences
E 3
I 3
.B scorefile
E 3
]
.SH DESCRIPTION
I 3
.I Robots
pits you against evil robots,
who are trying to kill you
(which is why they are evil).
Fortunately for you,
even though they are evil,
they are not very bright
and have a habit of bumping into each other,
thus destroying themselves.
In order to survive,
you must get them to kill each other off,
since you have no offensive weaponry.
E 3
.PP
D 3
The object of the game chase is to move around inside of the box on the
screen without getting eaten by the robots chasing and without running
into anything.
E 3
I 3
Since you are stuck without offensive weaponry,
you are endowed with one piece of defensive weaponry:
a teleportation device.
When two robots run into each other or a junk pile,
they die.
If a robot runs into you,
you die.
When a robot dies, you get 10 points,
and when all the robots die,
you start on the next field.
This keeps up until they finally get you.
E 3
.PP
D 3
If a robot runs into another robot while chasing you, they crash and leave
a junk heap.  If a robot runs into a fence, it is destroyed.
E 3
I 3
Robots are represented on the screen by a
.RB ` + ',
the junk heaps from their collisions by a
.RB ` \(** ',
and you
(the good guy)
by a
.RB ` @ '.
E 3
.PP
D 3
If you can survive until all the robots are destroyed, you have won!
E 3
I 3
The commands are:
.sp
.nf
.ta
.ta \w'\fBHJKLBNYU\fP\ \ 'u
\fBh\fP	move one square left
\fBl\fP	move one square right
\fBk\fP	move one square up
\fBj\fP	move one square down
\fBy\fP	move one square up and left
\fBu\fP	move one square up and right
\fBb\fP	move one square down and left
\fBn\fP	move one square down and right
\fB\&.\fP	(also space) do nothing for one turn
\fBHJKLBNYU\fP	run as far as possible in the given direction
\fB>\fP	do nothing for as long as possible
\fBt\fP	teleport to a random location
\fBw\fP	wait until you die or they all do
\fBq\fP	quit
\fB^L\fP	redraw the screen
.sp
.fi
All commands can be preceded by a count.
E 3
.PP
D 3
If you do not specify either
.I nrobots
or
.I nfences,
chase will prompt you for them.
E 3
I 3
If you use the
.RB ` w '
command and survive to the next level,
you will get a bonus of 10%
for each robot which died after you decided to wait.
If you die, however, you get nothing.
For all other commands,
the program will save you from typos
by stopping short of being eaten.
However,
with
.RB ` w '
you take the risk of dying by miscalculation.
.PP
Only five scores are allowed per user on the score file.
If you make it into the score file,
you will be shown the list at the end of the game.
If an alternate score file is specified,
that will be used instead of the standard file
for scores.
.PP
The options are
.TP
.B \-s
Don't play,
just show the score file
.TP
.B \-j
Jump,
.IR i.e. ,
when you run,
don't show any intermediate positions;
only show things at the end.
This is useful on slow terminals.
.TP
.B \-t
Teleport automatically when you have no other option.
This is a little disconcerting until you get used to it,
and then it is very nice.
.TP
.B \-a
Advance into the higher levels directly,
skipping the lower, easier levels.
.SH AUTHOR
Ken Arnold
.SH FILES
.ta
.ta \w'/usr/games/lib/robots_roll\ \ \ \ 'u
/usr/games/lib/robots_roll	the score file
.SH BUGS
Bugs?
You
.IR crazy ,
man?!?
E 3
D 2
.SH BUGS
E 2
E 1
