h44565
s 00001/00001/00025
d D 6.1 85/05/20 17:12:22 mckusick 3 2
c 4.3BSD beta release manual page
e
s 00004/00010/00022
d D 5.1 85/05/20 17:12:08 mckusick 2 1
c manual page distributed with 4.2BSD
e
s 00032/00000/00000
d D 4.1 85/05/20 17:12:00 mckusick 1 0
c manual page distributed with 4.1BSD
e
u
U
t
T
I 1
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH WUMP 6 
E 2
I 2
D 3
.TH WUMP 6  "1 February 1983"
E 3
I 3
.TH WUMP 6  "%Q%"
E 3
E 2
.AT 3
.SH NAME
wump \- the game of hunt-the-wumpus
.SH SYNOPSIS
.B /usr/games/wump
.SH DESCRIPTION
.I Wump
plays the game of `Hunt the Wumpus.'
A Wumpus is a creature that lives in a cave with several rooms
connected by tunnels.
You wander among the rooms, trying to
shoot the Wumpus with an arrow, meanwhile avoiding
D 2
being eaten by the Wumpus and falling
into
Bottomless Pits.
E 2
I 2
being eaten by the Wumpus and falling into Bottomless Pits.
E 2
There are also Super Bats which are likely to pick you up
and drop you in some random room.
.PP
D 2
The program asks various questions which you answer
one per line;
it will give a more detailed description
if you want.
E 2
I 2
The program asks various questions which you answer one per line;
it will give a more detailed description if you want.
E 2
.PP
This program is based on one described in
.I "People's Computer Company,"
.I 2,
2 (November 1973).
D 2
.SH BUGS
It will never replace Space War.
E 2
E 1
