h24493
s 00003/00001/00049
d D 7.1 88/05/21 18:33:10 karels 3 2
c bring up to revision 7 for tahoe release
e
s 00003/00003/00047
d D 1.2 87/12/22 12:33:58 bostic 2 1
c make ANSI C compatible
e
s 00050/00000/00000
d D 1.1 86/11/29 12:09:54 sam 1 0
c date and time created 86/11/29 12:09:54 by sam
e
u
U
t
T
I 1
D 3
/*	%M%	%I%	%E%	*/
E 3
I 3
/*
 *	%W% (Berkeley) %G%
 */
E 3

#ifndef _PSREG_
#define _PSREG_
/*
 * PS300 definitions.
 */
#ifndef KERNEL
#include <sys/ioctl.h>
#else
#include "../h/ioctl.h"
#endif

struct  pslookup {
        int     pl_len;                 /* length of name string */
        char    *pl_name;               /* address of name string */
        u_long  pl_addr;                /* symbol's address */
};

/*
 * Maximum string which may be supplied for lookup.
 */
#define PS_MAXNAMELEN   256             /* must be <= PSMAXDMA */

/*
 * When doing physical i/o, one may specify the address
 * and whether or not refresh sync should is required with
 * a null iovec descriptor (iov_len = 0).
 */
#define PSIO_SYNC       1               /* do physical write w/ refresh sync */

/*
 * Ioctl requests.
 */
D 2
#define PSIOGETERROR    _IOR(p, 0, int)                 /* get last error */
#define PSIOLOOKUP      _IOWR(p, 1, struct pslookup)    /* do name lookup */
#define PSIORWLOGICAL   _IOWR(p, 2, int)                /* set i/o mode */
E 2
I 2
#define PSIOGETERROR    _IOR('p', 0, int)                 /* get last error */
#define PSIOLOOKUP      _IOWR('p', 1, struct pslookup)    /* do name lookup */
#define PSIORWLOGICAL   _IOWR('p', 2, int)                /* set i/o mode */
E 2

/*
 * Error codes returned by PSIOGETERROR are either
 * returned by the PS300 or, from the list below,
 * generated by the device driver.
 */
#define PSERROR_DIOTIMO         1       /* timeout during dioread/diowrite */
#define PSERROR_INVALBC         2       /* invalid byte count for read/write */
#define PSERROR_BADADDR         3       /* invalid address for read/write */
#define PSERROR_BADCMD          4       /* invalid command in ikstart */
#define PSERROR_NAMETIMO        5       /* timeout during nameaddr dioread */
#define PSERROR_CMDTIMO         6       /* operation timed out */
#endif
E 1
