h36888
s 00013/00121/00018
d D 6.3 86/05/29 14:03:31 mckusick 4 3
c table of contents is more up to date
e
s 00019/00004/00120
d D 6.2 86/05/23 12:15:35 mckusick 3 2
c update for 4.3BSD
e
s 00001/00001/00123
d D 6.1 85/04/27 15:05:04 mckusick 2 1
c 4.3BSD beta release manual page
e
s 00124/00000/00000
d D 5.1 85/04/27 15:00:42 mckusick 1 0
c manual page first distributed with 4.2BSD
e
u
U
t
T
I 1
.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	%W% (Berkeley) %G%
.\"
D 2
.TH INTRO 8 "18 July 1983"
E 2
I 2
.TH INTRO 8 "%Q%"
E 2
.UC 5
.SH NAME
intro \- introduction to system maintenance and operation commands
.SH DESCRIPTION
This section contains information related to system operation
D 4
and maintenance.  In particular, commands used to create new file
systems,
E 4
I 4
and maintenance.
It describes commands used to create new file systems,
E 4
.IR newfs ,
D 4
.IR mkfs ,
and verify the integrity of the file systems,
E 4
I 4
verify the integrity of the file systems,
E 4
.IR fsck ,
D 4
.IR icheck ,
.IR dcheck ,
and
.I ncheck
are described
here.  The section 
E 4
I 4
control disk usage,
.IR edquota ,
maintain system backups,
.IR dump ,
and recover files when disks die an untimely death,
.IR restore .
The section 
E 4
.I format
D 4
should be consulted when formatting disk packs.  The section
E 4
I 4
should be consulted when formatting disk packs.
Network related services are distinguished as 8C.
The section
E 4
.I crash
should be consulted in understanding how to interpret system
crash dumps.
D 4
.SH "LIST OF PROGRAMS"
.sp 2
.nf
.ta \w'mklost+found'u+2n +\w'mklost+found.8'u+10n
\fIProgram\fP	\fIAppears on Page\fP	\fIDescription\fP
.ta \w'mklost+found'u+4n +\w'mklost+found.8'u+4n
.sp 5p
ac	ac.8	login accounting
accton	sa.8	system accounting
D 3
adduser	adduser.8	procedure for adding new users
analyze	analyze.8	Virtual UNIX postmortem crash analyzer
arcv	arcv.8	convert archives to new format
E 3
I 3
adduser	adduser.8	procedures for adding new users
E 3
arff	arff.8v	archiver and copier for floppy
I 3
arp	arp.8c	address resolution display and control
E 3
bad144	bad144.8	read/write dec standard 144 bad sector information
badsect	badsect.8	create files to contain bad sectors
bugfiler	bugfiler.8	file bug reports in folders automatically
catman	catman.8	create the cat files for the manual
chown	chown.8	change owner
clri	clri.8	clear i-node
comsat	comsat.8c	biff server
config	config.8	build system configuration files
crash	crash.8v	what happens when the system crashes
cron	cron.8	clock daemon
dcheck	dcheck.8	file system directory consistency check
diskpart	diskpart.8	calculate default disk partition sizes
dmesg	dmesg.8	collect system diagnostic messages to form error log
drtest	drtest.8	standalone disk test program
dump	dump.8	incremental file system dump
dumpfs	dumpfs.8	dump file system information
edquota	edquota.8	edit user quotas
fastboot	fastboot.8	reboot/halt the system without checking the disks
fasthalt	fastboot.8	reboot/halt the system without checking the disks
I 3
fingerd	fingerd.8c	remote user information server
E 3
flcopy	arff.8v	archiver and copier for floppy
format	format.8v	how to format disk packs
fsck	fsck.8	file system consistency check and interactive repair
ftpd	ftpd.8c	DARPA Internet File Transfer Protocol server
gettable	gettable.8c	get NIC format host tables from a host 
getty	getty.8	set terminal mode
halt	halt.8	stop the processor
htable	htable.8	convert NIC standard format host tables
icheck	icheck.8	file system storage consistency check
ifconfig	ifconfig.8c	configure network interface parameters
implog	implog.8c	IMP log interpreter
implogd	implogd.8c	IMP logger process
I 3
inetd	inetd.8	internet ``super\-server''
E 3
init	init.8	process control initialization
kgmon	kgmon.8	generate a dump of the operating systems profile buffers
lpc	lpc.8	line printer control program
lpd	lpd.8	line printer daemon
makedev	makedev.8	make system special files
makekey	makekey.8	generate encryption key
mkfs	mkfs.8	construct a file system
I 3
mkhosts	mkhosts.8	generate hashed host table
E 3
mklost+found	mklost+found.8	make a lost+found directory for fsck
mknod	mknod.8	build special file
I 3
mkpasswd	mkpasswd.8	generate hashed password table
E 3
mkproto	mkproto.8	construct a prototype file system
mount	mount.8	mount and dismount file system
I 3
named	named.8	Internet domain name server
E 3
ncheck	ncheck.8	generate names from i-numbers
newfs	newfs.8	construct a new file system
pac	pac.8	printer/ploter accounting information
I 3
ping	ping.8	send ICMP ECHO_REQUEST packets to network hosts
E 3
pstat	pstat.8	print system facts
quot	quot.8	summarize file system ownership
quotacheck	quotacheck.8	file system quota consistency checker
quotaoff	quotaon.8	turn file system quotas on and off
quotaon	quotaon.8	turn file system quotas on and off
rc	rc.8	command script for auto-reboot and daemons
rdump	rdump.8c	file system dump across the network
reboot	reboot.8	UNIX bootstrapping procedures
renice	renice.8	alter priority of running processes
repquota	repquota.8	summarize quotas for a file system
restore	restore.8	incremental file system restore
rexecd	rexecd.8c	remote execution server
rlogind	rlogind.8c	remote login server
rmt	rmt.8c	remote magtape protocol module
route	route.8c	manually manipulate the routing tables
routed	routed.8c	network routing daemon
rrestore	rrestore.8c	restore a file system dump across the network
rshd	rshd.8c	remote shell server
rwhod	rwhod.8c	system status server
rxformat	rxformat.8v	format floppy disks
sa	sa.8	system accounting
savecore	savecore.8	save a core dump of the operating system
sendmail	sendmail.8	send mail over the internet
shutdown	shutdown.8	close down the system at a given time
I 3
slattach	slattach.8c	attach serial lines as network interfaces
E 3
sticky	sticky.8	executable files with persistent text
swapon	swapon.8	specify additional device for paging and swapping
sync	sync.8	update the super block
D 3
syslog	syslog.8	log systems messages
E 3
I 3
syslogd	syslogd.8	log systems messages
talkd	talkd.8c	remote user communications server
E 3
telnetd	telnetd.8c	DARPA TELNET protocol server
tftpd	tftpd.8c	DARPA Trivial File Transfer Protocol server
I 3
timed	timed.8	time server daemon
timedc	timedc.8	timed control program
E 3
trpt	trpt.8c	transliterate protocol trace
I 3
trsp	trsp.8c	transliterate sequenced packet protocol trace
E 3
tunefs	tunefs.8	tune up an existing file system
umount	mount.8	mount and dismount file system
update	update.8	periodically update the super block
I 3
uucico	uucico.8c	transfer files queued by uucp or uux
uucpd	uucico.8c	transfer files queued by uucp or uux
E 3
uuclean	uuclean.8c	uucp spool directory clean-up
I 3
uupoll	uupoll.8c	poll a remote UUCP site
E 3
uusnap	uusnap.8c	show snapshot of the UUCP system
I 3
uuxqt	uuxqt.8c	UUCP execution file interpreter
E 3
vipw	vipw.8	edit the password file
I 3
XNSrouted	XNSrouted.8c	NS Routing Information Protocol daemon
E 4
E 3
E 1
